- name: Send Discord Embed Notification if status changed
  if: env.STATUS_CODE != ''
  run: |
    TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    if [ "$STATUS_CODE" -eq 200 ] && [ "$PREV_STATUS" != "UP" ]; then
      curl -X POST -H "Content-Type: application/json" -d @- "${{ secrets.DISCORD_WEBHOOK }}" <<EOF
{
  "embeds": [{
    "title": "🟢 Mentari UNPAM BACK UP",
    "description": "Website sudah kembali online.",
    "color": 3066993,
    "fields": [
      {"name": "URL", "value": "https://mentari.unpam.ac.id/", "inline": true},
      {"name": "Status Code", "value": "$STATUS_CODE", "inline": true},
      {"name": "Time (UTC)", "value": "$TIMESTAMP", "inline": false}
    ]
  }]
}
EOF
      echo "UP" > status.txt

    elif [ "$STATUS_CODE" -ne 200 ] && [ "$PREV_STATUS" != "DOWN" ]; then
      curl -X POST -H "Content-Type: application/json" -d @- "${{ secrets.DISCORD_WEBHOOK }}" <<EOF
{
  "embeds": [{
    "title": "🔴 Mentari UNPAM DOWN",
    "description": "Website sedang tidak dapat diakses!",
    "color": 15158332,
    "fields": [
      {"name": "URL", "value": "https://mentari.unpam.ac.id/", "inline": true},
      {"name": "Status Code", "value": "$STATUS_CODE", "inline": true},
      {"name": "Time (UTC)", "value": "$TIMESTAMP", "inline": false}
    ]
  }]
}
EOF
      echo "DOWN" > status.txt
    else
      echo "✅ Status unchanged - No notification needed"
